name: Publish doctor to GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Publish package
        run: mvn --batch-mode clean package deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
